name: Plots
version: 0.1
main: com.github.DarkSeraphim.Plots.Plots
author: Fireblast709
depend: [Essentials]

commands:
  plots:
    description: main Plots command
    default: true
    
permissions:
  plots.*:
    children:
      plots.claim: true
      plots.noclaim: true
      plots.list.other: true
  plots.claim:
    description: Permission for claiming chunks
    default: true
  plots.noclaim:
    description: Permission for claiming noclaim chunks
    default: op
  plots.list.other:
    description: Permission to list other people's claimed chunks
  plots.unclaim.other:
    description: Unclaim other plots